kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: todonodejs
    name: frontend 
  name: frontend
spec:  
  host: prod-todo.apps.ocp4.example.com
  path: "/todo"
  to:
    kind: Service
    name: prod-frontend
    weight: 100
  wildcardPolicy: None

